name: Checks

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install codecov coverage flake8 pytest pytest-benchmark
        # install dependencies
        pip install -e .[all]
        # show installed packages
        pip freeze
    - name: Benchmark with pytest-benchmark
      run: |
        pytest tests/benchmarking_tests --benchmark-json="output.json" --benchmark-compare="*/ActionsBenchmark_190321_UBUNTUpy38" --benchmark-compare-fail=median:5%
        cat output.json
    - name: Test with pytest
      run: |
        coverage run -m --source=shapelink pytest --ignore=tests/benchmarking_tests
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Submit code coverage
      run: |
        coverage report -m
        codecov
